### ISSUE TITLE
Exception 9: LoadStoreAlignmentCause: Load or store to an unaligned address

### ISSUE THREAD

**Issue by Calimerorulez** [shortbloke/Broadband_Usage_Display#4]
Hi,

I'm trying to get the cool display to work, but I'm getting a crash and a stack trace. I tried to debug, and it seems that it crashes in SNMPGet.h of Arduino_SNMP_Manager

The function sendTo is called and then it crashes in the line `int length = packet->serialise(_packetBuffer);`

I'm using the fixed bandwidth sketch, Arduino IDE 1.8.15, ESP-bord software v3.0.0 for Arduino, and your latest libraries.

The debug is as follows:

```
Exception 9: LoadStoreAlignmentCause: Load or store to an unaligned address
PC: 0x40100caf
EXCVADDR: 0x40000f65

Decoding stack results
0x4020581a: loop_task(ETSEvent*) at C:\Users\pat\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.0\cores\esp8266\core_esp8266_main.cpp line 213
0x40201128: OctetType::serialise(unsigned char*) at C:\Users\pat\Documents\Arduino\libraries\Arduino_SNMP_Manager-master\src/BER.h line 215
0x402058a0: __esp_yield() at C:\Users\pat\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.0\cores\esp8266/core_esp8266_features.h line 65
0x402061ca: __delay(unsigned long) at C:\Users\pat\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.0\cores\esp8266\core_esp8266_wiring.cpp line 54
0x402014a5: ComplexType::serialise(unsigned char*) at C:\Users\pat\Documents\Arduino\libraries\Arduino_SNMP_Manager-master\src/BER.h line 630
0x40201b5d: SNMPGet::sendTo(IPAddress) at C:\Users\pat\Documents\Arduino\libraries\Arduino_SNMP_Manager-master\src/SNMPGet.h line 76
0x4020a807: rand at /workdir/repo/newlib/newlib/libc/stdlib/rand.c line 79
0x40202914: getSNMP() at C:\Users\pat\Documents\Arduino\libraries\Arduino_SNMP_Manager-master\src/SNMPGet.h line 92
0x40203936: millisDelay::justFinished() at C:\Users\pat\Documents\Arduino\libraries\SafeString\src\millisDelay.cpp line 76
0x40202977: loop() at C:\Users\pat\Documents\Arduino\BWMonitor/BWMonitor.ino line 121
0x402059cc: loop_wrapper() at C:\Users\pat\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.0\cores\esp8266\core_esp8266_main.cpp line 201
```

Is there a way I can get it to work? Thanks again.

**Comment by shortbloke** [comment]
Hi, can you confirm the OID you are querying, it looks to be an OCTETSTRING, there can be problems with the length of strings and also the complex nature in how they are decoded. I have also seen issues that required that the max packet length be reduced, can you try a lower packet length than 968?
```
#elif defined(ESP8266)
#define SNMP_PACKET_LENGTH 968 
```

If this is for a bandwidth monitor then I'd discourage the querying of OCTETSTRINGS due to the additional memory requirements. Instead, focus on just getting the numeric values needed for the calculations.

If you can use SNMP walk or iReasoning MIB Browser to confirm the types and the response that would be useful.
Failing all that, then a Wireshark capture would probably be required to see what about the packet structure is causing the crash.

It may also be worth testing with board software 2.7.4 which is what I have used, just in case the issue is caused by the latest 3.0.0 version.

**Comment by Calimerorulez** [comment]
> Hi, can you confirm the OID you are querying, it looks to be an OCTETSTRING, there can be problems with the length of strings and also the complex nature in how they are decoded. I have also seen issues that required that the max packet length be reduced, can you try a lower packet length than 968?
> 
> ```
> #elif defined(ESP8266)
> #define SNMP_PACKET_LENGTH 968 
> ```
> 
> If this is for a bandwidth monitor then I'd discourage the querying of OCTETSTRINGS due to the additional memory requirements. Instead, focus on just getting the numeric values needed for the calculations.
> 
> If you can use SNMP walk or iReasoning MIB Browser to confirm the types and the response that would be useful.
> Failing all that, then a Wireshark capture would probably be required to see what about the packet structure is causing the crash.
> 
> It may also be worth testing with board software 2.7.4 which is what I have used, just in case the issue is caused by the latest 3.0.0 version.

Hi,

Thank you for your quick reply. The OID I'm querying is a counter32. I've changed the packet length to 750, and it seems to work fine now. I will test a little bit further :)
